In [5]:
import numpy as np

#### Scalars--0 dimenion

In [6]:
s = np.array(5)
s.shape

()

In [7]:
x=s+3
print x

8


### 1 Dimension:Vector


In [10]:
v = np.array([1,2,3])
v.shape

(3L,)

Shape tuple with size of each dimension

In [11]:
x=v[1]
print x

2


In [13]:
print v[1:]

[2 3]


####  2 Dimension: Matrices 

In [17]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
m.shape

(3L, 3L)

In [18]:
print m[1][2]

6


#### N-Dimensional Tensors

In [19]:
#3x3x2x1 tensor 
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [20]:
print t[2][1][1][0]

16


In [21]:
print t[2][1][1][1]

IndexError: index 1 is out of bounds for axis 0 with size 1

Changing Shapes


In [7]:
v = np.array([1,2,3,4])
print (v.shape)

(4,)


In [8]:
v.reshape(1,4)

array([[1, 2, 3, 4]])

In [9]:
v.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [10]:
v.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [11]:
v.reshape(2,3)

ValueError: cannot reshape array of size 4 into shape (2,3)

In [12]:
x = v[None, :]
print (x)

[[1 2 3 4]]


In [14]:
x = v[ :,None]
print (x)

[[1]
 [2]
 [3]
 [4]]


In [5]:
import numpy as np
activation_function = lambda x : 1/(1+np.exp(-x))

In [7]:
activation_function(-0.18)

0.45512110762641994